# Generated by Django 3.0.4 on 2020-03-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('evolves_from_species', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_species', to='pokemon_species.PokemonSpecies', verbose_name='evolves_from_species')),
            ],
        ),
    ]
