# Generated by Django 3.0.4 on 2020-03-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='evolves_from_species',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_species', to='pokemon_species.PokemonSpecies', verbose_name='evolves_from_species'),
        ),
    ]
