# Generated by Django 3.0.4 on 2020-03-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_species', '0002_auto_20200325_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonspecies',
            name='evolves_from_species',
        ),
    ]
