# Generated by Django 3.0.4 on 2020-03-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon_species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolves_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chain_link', to='evolution.ChainLink', verbose_name='evolves_to')),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chain_link', to='pokemon_species.PokemonSpecies', verbose_name='species')),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolution_chain', to='evolution.ChainLink', verbose_name='chain')),
            ],
        ),
    ]
