# Generated by Django 3.0.4 on 2020-03-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionchain',
            name='chain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evolution_chain', to='evolution.ChainLink', verbose_name='chain'),
        ),
    ]
