# Generated by Django 3.0.4 on 2020-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0002_auto_20200325_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainlink',
            name='evolves_to',
        ),
        migrations.AddField(
            model_name='chainlink',
            name='evolves_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='_chainlink_evolves_to_+', to='evolution.ChainLink', verbose_name='evolves_to'),
        ),
    ]
