# Generated by Django 3.0.4 on 2020-03-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0004_auto_20200325_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainlink',
            name='evolves_to',
        ),
        migrations.AddField(
            model_name='chainlink',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chain_link', to='evolution.ChainLink', verbose_name='evolves_from'),
        ),
    ]
